service: plate-invoice-paid

provider:
  name: aws
  runtime: nodejs22.x
  timeout: 30
  environment:
    MONGO_URL: ${env:MONGO_URL}
    BOTCONVERSA_TOKEN: ${env:BOTCONVERSA_TOKEN}
    AWS_REGION: ${env:AWS_REGION}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}

  stage: production

functions:
  retrievePlate:
    handler: index.handler
    events:
      - http:
          path: plate-invoice-paid
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3005
